# Generated by Django 5.0.6 on 2024-06-14 09:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_ru', models.CharField(max_length=120)),
                ('title_kg', models.CharField(max_length=120)),
                ('title_tu', models.CharField(max_length=120)),
                ('title_en', models.CharField(max_length=120)),
                ('image', models.ImageField(upload_to='categories/')),
                ('link', models.CharField(max_length=120)),
                ('is_about', models.BooleanField(default=False)),
                ('is_constructr', models.BooleanField(default=False)),
                ('is_collagen', models.BooleanField(default=False)),
                ('is_coffe', models.BooleanField(default=False)),
                ('is_tea', models.BooleanField(default=False)),
                ('is_drink', models.BooleanField(default=False)),
                ('is_bar', models.BooleanField(default=False)),
                ('is_smuzi', models.BooleanField(default=False)),
                ('is_wine', models.BooleanField(default=False)),
                ('is_sale', models.BooleanField(default=False)),
                ('number', models.IntegerField(blank=True, default=0, null=True)),
            ],
            options={
                'db_table': 'categories',
            },
        ),
        migrations.CreateModel(
            name='SVG',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('svg', models.FileField(upload_to='svgs/')),
            ],
            options={
                'db_table': 'svgs',
            },
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_ru', models.CharField(max_length=120)),
                ('title_kg', models.CharField(max_length=120)),
                ('title_tu', models.CharField(max_length=120)),
                ('title_en', models.CharField(max_length=120)),
                ('custom_orange_ru', models.CharField(blank=True, max_length=120, null=True)),
                ('custom_orange_kg', models.CharField(blank=True, max_length=120, null=True)),
                ('custom_orange_tu', models.CharField(blank=True, max_length=120, null=True)),
                ('custom_orange_en', models.CharField(blank=True, max_length=120, null=True)),
                ('custom_black_ru', models.CharField(blank=True, max_length=120, null=True)),
                ('custom_black_kg', models.CharField(blank=True, max_length=120, null=True)),
                ('custom_black_tu', models.CharField(blank=True, max_length=120, null=True)),
                ('custom_black_en', models.CharField(blank=True, max_length=120, null=True)),
                ('main_title_ru', models.CharField(blank=True, max_length=120, null=True)),
                ('main_title_kg', models.CharField(blank=True, max_length=120, null=True)),
                ('main_title_tu', models.CharField(blank=True, max_length=120, null=True)),
                ('main_title_en', models.CharField(blank=True, max_length=120, null=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dishes.category')),
            ],
            options={
                'db_table': 'subcategories',
            },
        ),
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_ru', models.CharField(max_length=120)),
                ('title_kg', models.CharField(max_length=120)),
                ('title_tu', models.CharField(max_length=120)),
                ('title_en', models.CharField(max_length=120)),
                ('image', models.ImageField(upload_to='dishes/')),
                ('text_ru', models.TextField(blank=True, null=True)),
                ('text_kg', models.TextField(blank=True, null=True)),
                ('text_tu', models.TextField(blank=True, null=True)),
                ('text_en', models.TextField(blank=True, null=True)),
                ('advice_ru', models.TextField(blank=True, null=True)),
                ('advice_kg', models.TextField(blank=True, null=True)),
                ('advice_tu', models.TextField(blank=True, null=True)),
                ('advice_en', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('weight', models.IntegerField(blank=True, default=0, null=True)),
                ('subcategory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dishes.subcategory')),
                ('svgs', models.ManyToManyField(blank=True, to='dishes.svg')),
            ],
            options={
                'db_table': 'dishes',
            },
        ),
    ]
